#!/bin/bash

# another sample script to pump in data from the current time
# Usage: ./currente_time_data localhost 153
NOW=$(date +"%s")
DOCKER=$1
curl --data "{\"check_id\": \"mic3\", \"time\":$NOW, \"value\":$2, \"config\" : {\"resolution\" : 1}}" http://$DOCKER:8080
